#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
echo "Running Typecheck and Linting..."

npm run typecheck && npm run lint && echo "✅ All checks passed!" || {
  echo "❌ Typecheck or Linting failed. Please fix the issues before committing."
  exit 1
}
