#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🔍 Running typecheck and lint-staged..."

npm run precommit

if [ $? -eq 0 ]; then
  echo "✅ All checks passed. Proceeding with commit."
else
  echo "❌ Checks failed. Commit aborted."
  exit 1
fi
